name: asset_management
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  archive: ^3.6.1
  bloc: ^9.0.0
  dartz: ^0.10.1
  data_table_2: ^2.6.0
  device_preview: ^1.3.1
  dropdown_search: ^6.0.2
  equatable: ^2.0.7
  excel: ^4.0.6
  file_picker: ^10.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  go_router: ^17.0.0
  http: ^1.5.0
  intl: ^0.20.2
  open_file: ^3.5.10
  open_filex: ^4.7.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  toastification: ^3.0.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/logo-watsons.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
